services:
  app:
    container_name: ${PROJECT_NAME}-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    command: ["npm", "run", "dev"]
