export const usePatients = [
  {
    rut: '15283291-9',
    nombre: 'José Torres',
    categoría: 'Melanoma',
    urgencia: 5,
  },
  {
    rut: '19676071-4',
    nombre: 'Luis Fernández',
    categoría: 'Cancer',
    urgencia: 10,
  },
  {
    rut: '17907924-5',
    nombre: 'Luis Fernández',
    categoría: 'Cancer',
    urgencia: 7,
  },
  {
    rut: '2517443-0',
    nombre: 'Luis Fernández',
    categoría: 'Melanoma',
    urgencia: 1,
  },
  {
    rut: '19812472-1',
    nombre: 'Ana González',
    categoría: 'Melanoma',
    urgencia: 6,
  },
  {
    rut: '11026679-4',
    nombre: 'María López',
    categoría: 'Melanoma',
    urgencia: 10,
  },
  {
    rut: '9003650-6',
    nombre: 'Miguel Sánchez',
    categoría: 'Melanoma',
    urgencia: 5,
  },
  {
    rut: '8763837-3',
    nombre: 'Carmen Martínez',
    categoría: 'Melanoma',
    urgencia: 9,
  },
  {
    rut: '5094043-5',
    nombre: 'Miguel Sánchez',
    categoría: 'Cancer',
    urgencia: 9,
  },
  {
    rut: '23218323-1',
    nombre: 'María López',
    categoría: 'Cancer',
    urgencia: 4,
  },
  {
    rut: '22440608-5',
    nombre: 'Juan Pérez',
    categoría: 'Melanoma',
    urgencia: 8,
  },
  {
    rut: '17720502-0',
    nombre: 'Lucía Morales',
    categoría: 'Melanoma',
    urgencia: 4,
  },
  {
    rut: '1745628-6',
    nombre: 'Juan Pérez',
    categoría: 'Melanoma',
    urgencia: 9,
  },
  {
    rut: '19478060-7',
    nombre: 'Luis Fernández',
    categoría: 'Melanoma',
    urgencia: 5,
  },
  {
    rut: '3582851-1',
    nombre: 'Laura Ramírez',
    categoría: 'Cancer',
    urgencia: 1,
  },
  {
    rut: '12071988-2',
    nombre: 'Miguel Sánchez',
    categoría: 'Cancer',
    urgencia: 3,
  },
  {
    rut: '5647610-9',
    nombre: 'Ana González',
    categoría: 'Melanoma',
    urgencia: 1,
  },
  {
    rut: '19887148-5',
    nombre: 'Juan Pérez',
    categoría: 'Cancer',
    urgencia: 3,
  },
  {
    rut: '21614204-6',
    nombre: 'Ana González',
    categoría: 'Cancer',
    urgencia: 2,
  },
  {
    rut: '2861829-2',
    nombre: 'José Torres',
    categoría: 'Melanoma',
    urgencia: 6,
  },
  {
    rut: '18511543-7',
    nombre: 'Juan Pérez',
    categoría: 'Melanoma',
    urgencia: 8,
  },
  {
    rut: '15591848-3',
    nombre: 'Lucía Morales',
    categoría: 'Melanoma',
    urgencia: 3,
  },
  {
    rut: '16631120-2',
    nombre: 'José Torres',
    categoría: 'Melanoma',
    urgencia: 6,
  },
  {
    rut: '20770991-3',
    nombre: 'Lucía Morales',
    categoría: 'Cancer',
    urgencia: 6,
  },
  {
    rut: '24688568-5',
    nombre: 'José Torres',
    categoría: 'Melanoma',
    urgencia: 9,
  },
  {
    rut: '6856402-K',
    nombre: 'Juan Pérez',
    categoría: 'Melanoma',
    urgencia: 10,
  },
  {
    rut: '19534890-5',
    nombre: 'Lucía Morales',
    categoría: 'Melanoma',
    urgencia: 9,
  },
  {
    rut: '13454328-6',
    nombre: 'José Torres',
    categoría: 'Cancer',
    urgencia: 9,
  },
  {
    rut: '19104547-7',
    nombre: 'Ana González',
    categoría: 'Cancer',
    urgencia: 9,
  },
  {
    rut: '16697623-5',
    nombre: 'Laura Ramírez',
    categoría: 'Cancer',
    urgencia: 4,
  },
  {
    rut: '20140539-0',
    nombre: 'José Torres',
    categoría: 'Cancer',
    urgencia: 8,
  },
  {
    rut: '5668545-7',
    nombre: 'Ana González',
    categoría: 'Cancer',
    urgencia: 5,
  },
  {
    rut: '5331345-9',
    nombre: 'Lucía Morales',
    categoría: 'Cancer',
    urgencia: 7,
  },
];
