export const usePatients = [
  {
    id: 1,
    rut: '15283291-9',
    nombre: 'José Torres',
    categoría: 'Melanoma',
    urgencia: 5,
  },
  {
    id: 2,
    rut: '19676071-4',
    nombre: 'Luis Fernández',
    categoría: 'Cancer',
    urgencia: 10,
  },
  {
    id: 3,
    rut: '17907924-5',
    nombre: 'Luis Fernández',
    categoría: 'Cancer',
    urgencia: 7,
  },
  {
    id: 4,
    rut: '2517443-0',
    nombre: 'Luis Fernández',
    categoría: 'Melanoma',
    urgencia: 1,
  },
  {
    id: 5,
    rut: '19812472-1',
    nombre: 'Ana González',
    categoría: 'Melanoma',
    urgencia: 6,
  },
  {
    id: 6,
    rut: '11026679-4',
    nombre: 'María López',
    categoría: 'Melanoma',
    urgencia: 10,
  },
  {
    id: 7,
    rut: '9003650-6',
    nombre: 'Miguel Sánchez',
    categoría: 'Melanoma',
    urgencia: 5,
  },
  {
    id: 8,
    rut: '8763837-3',
    nombre: 'Carmen Martínez',
    categoría: 'Melanoma',
    urgencia: 9,
  },
  {
    id: 9,
    rut: '5094043-5',
    nombre: 'Miguel Sánchez',
    categoría: 'Cancer',
    urgencia: 9,
  },
  {
    id: 10,
    rut: '23218323-1',
    nombre: 'María López',
    categoría: 'Cancer',
    urgencia: 4,
  },
  {
    id: 11,
    rut: '22440608-5',
    nombre: 'Juan Pérez',
    categoría: 'Melanoma',
    urgencia: 8,
  },
  {
    id: 12,
    rut: '17720502-0',
    nombre: 'Lucía Morales',
    categoría: 'Melanoma',
    urgencia: 4,
  },
  {
    id: 13,
    rut: '1745628-6',
    nombre: 'Juan Pérez',
    categoría: 'Melanoma',
    urgencia: 9,
  },
  {
    id: 14,
    rut: '19478060-7',
    nombre: 'Luis Fernández',
    categoría: 'Melanoma',
    urgencia: 5,
  },
  {
    id: 15,
    rut: '3582851-1',
    nombre: 'Laura Ramírez',
    categoría: 'Cancer',
    urgencia: 1,
  },
  {
    id: 16,
    rut: '12071988-2',
    nombre: 'Miguel Sánchez',
    categoría: 'Cancer',
    urgencia: 3,
  },
  {
    id: 17,
    rut: '5647610-9',
    nombre: 'Ana González',
    categoría: 'Melanoma',
    urgencia: 1,
  },
  {
    id: 18,
    rut: '19887148-5',
    nombre: 'Juan Pérez',
    categoría: 'Cancer',
    urgencia: 3,
  },
  {
    id: 19,
    rut: '21614204-6',
    nombre: 'Ana González',
    categoría: 'Cancer',
    urgencia: 2,
  },
  {
    id: 20,
    rut: '2861829-2',
    nombre: 'José Torres',
    categoría: 'Melanoma',
    urgencia: 6,
  },
  {
    id: 21,
    rut: '18511543-7',
    nombre: 'Juan Pérez',
    categoría: 'Melanoma',
    urgencia: 8,
  },
  {
    id: 22,
    rut: '15591848-3',
    nombre: 'Lucía Morales',
    categoría: 'Melanoma',
    urgencia: 3,
  },
  {
    id: 23,
    rut: '16631120-2',
    nombre: 'José Torres',
    categoría: 'Melanoma',
    urgencia: 6,
  },
  {
    id: 24,
    rut: '20770991-3',
    nombre: 'Lucía Morales',
    categoría: 'Cancer',
    urgencia: 6,
  },
  {
    id: 25,
    rut: '24688568-5',
    nombre: 'José Torres',
    categoría: 'Melanoma',
    urgencia: 9,
  },
  {
    id: 26,
    rut: '6856402-K',
    nombre: 'Juan Pérez',
    categoría: 'Melanoma',
    urgencia: 10,
  },
  {
    id: 27,
    rut: '19534890-5',
    nombre: 'Lucía Morales',
    categoría: 'Melanoma',
    urgencia: 9,
  },
  {
    id: 28,
    rut: '13454328-6',
    nombre: 'José Torres',
    categoría: 'Cancer',
    urgencia: 9,
  },
  {
    id: 29,
    rut: '19104547-7',
    nombre: 'Ana González',
    categoría: 'Cancer',
    urgencia: 9,
  },
  {
    id: 30,
    rut: '16697623-5',
    nombre: 'Laura Ramírez',
    categoría: 'Cancer',
    urgencia: 4,
  },
  {
    id: 31,
    rut: '20140539-0',
    nombre: 'José Torres',
    categoría: 'Cancer',
    urgencia: 8,
  },
  {
    id: 32,
    rut: '5668545-7',
    nombre: 'Ana González',
    categoría: 'Cancer',
    urgencia: 5,
  },
  {
    id: 33,
    rut: '5331345-9',
    nombre: 'Lucía Morales',
    categoría: 'Cancer',
    urgencia: 7,
  },
];
